name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y git
        
    - name: Install Python dependencies
      run: pip install -r requirements.txt
      
    - name: Build documentation
      run: mkdocs build --site-dir test
      
    - name: Upload test build
      uses: actions/upload-artifact@v3
      with:
        name: test-docs
        path: test/

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y git
        
    - name: Install Python dependencies
      run: pip install -r requirements.txt
      
    - name: Build documentation
      run: |
        export ENABLED_GIT_REVISION_DATE="true"
        mkdocs build --site-dir public
      
    - name: Setup Pages
      uses: actions/configure-pages@v3
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: public/
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2